site_name: Courses Learning
site_description: A website stored my notes for self-learning courses.
site_author: Zhidong Zhang

repo_name: Harbour-z/Course_learning # 仓库名称
repo_url: https://github.com/Harbour-z/Course_learning.git/ # 仓库地址

copyright: Copyright &copy; 2024 ~ now | Zhidong Zhang
nav:
    - 首页: index.md
    - MIT 6.092:
      - '': mit6.092\index.md
    - 动手学深度学习:
      - '': d2l\index.md
    - FishBook:
      - FishBook1:
        - '': FishBook\FishBook1\index.md
theme:
  #custom_dir: material/overrides # 自定义文件夹，对于个别页面，如果你不想使用主题的默认样式，可以在这里进行修改，使用里面的文件覆盖主题的默认文件。具体可以参考material官方文档。
  name: material # 主题名称，Material已经是最优秀的选择了，相信我。
  #logo: static/images/logo.png # logo 图片
  language: zh
  
  palette:
    #primary: blue grey
    - scheme: default # 日间模式
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - content.code.copy # 代码内容给一个复制按钮
    - content.code.annotate # 代码块内的注释
    - content.action.edit # 编辑按钮，似乎没啥用
    - content.action.view # 查看按钮，似乎没啥用
    # - navigation
    - navigation.tabs   #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.expand
    #- toc.integrate 目录与导航集成
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    # - navigation.sections # 导航栏的section
    - content.code.copy
    - navigation.footer
    - navigation.top
    - navigation.tabs 
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlighting   # 搜索出的文章关键词加入高亮
    #- navigation.indexes   #启用节索引页后，可以将文档直接附加到节
    - search.share   #搜索分享按钮
    - header.autohide
    - toc.follow


plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Harbour-z
    - icon: fontawesome/solid/paper-plane
      link: mailto:<814287468@qq.com>
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zhidong--zhang/

  version: 1.0

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences  #超级围栏
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.extensions.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js
# alternate:
#     - name: English
#       link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp 
#       lang: en


